### ISSUE TITLE
Nutrimatic sometimes returns answers of incorrect length

### ISSUE THREAD

**Issue by supersandra** [PuzzleTechHub/nutrimatic#10]
Two nights ago (probably ~12AM Pacific Time on Nov 22, 2023), I ran the following query: 
`"[zoesaldana][sewingroom][falsefears][evidential][cringingat][ianfleming][sewingroom][escapedcon]A[blankcheck]"`

The URL of my request, for reference, was: 
`https://nutrimatic.org/?q=%22%5Bzoesaldana%5D%5Bsewingroom%5D%5Bfalsefears%5D%5Bevidential%5D%5Bcringingat%5D%5Bianfleming%5D%5Bsewingroom%5D%5Bescapedcon%5DA%5Bblankcheck%5D%22&go=Go`

At the time, it returned results that included many 10-letter results but also the word `deficient` and at least one other 9-letter result that I no longer recall (I think it also started with a `d`).

At the time of writing, it seems to only be returning 10-letter results (as it should given the query).

I don't know if this sort of transient error is already known or not, but I figured I'd file a but in case it is not.

(Also, thanks for offering this awesome tool!)

**Comment by egnor** [comment]
(Weird!)

**Comment by egnor** [comment]
aha, I think I figured it out, using this URL, which you (or someone! but presumably you!) submitted around that time: https://nutrimatic.org/?q=%22%5Bzoesaldana%5D%5Bsewingroom%5D%5Bfalsefears%5D%5Bevidential%5D%5Bcringingat%5D%5Bianfleming%5D%5Bsewingroom%5D%5Bescapedcon%5D%5Btheshining%5D%5Bblankcheck%5D%22&go=Go

Nutrimatic gives the expected results, including `deficiente`, but Google Chrome then decides to recognize it as Italian and automatically translate it, turning `deficiente` into `deficient`:
![image](https://github.com/egnor/nutrimatic/assets/279819/c22c6b07-966f-4b15-bf5e-fffe13c920b9)

Toggling back to the original "Italian", I see the expected results:
![image](https://github.com/egnor/nutrimatic/assets/279819/bd229b7c-fbd3-48cc-b643-5e7b2d787520)

I probably enabled this translation by default at some point? And apparently so did you?

I'm closing this issue, but if this explanation doesn't seem plausible to you then please reopen!

**Comment by supersandra** [comment]
Yup, that looks to be it! What a wild thing that is.

Thanks for looking into it!
