### ISSUE TITLE
Incorrect matches for certain anagrams

### ISSUE THREAD

**Issue by rdeits** [PuzzleTechHub/nutrimatic#6]
First of all, thanks for creating such a great tool! 

I just ran a query over at nutrimatic.org and came across what appears to be an incorrect set of outputs. The specific query was: `<blsaemA[ef]>` for which nutrimatic produced such outputs as: 

```
assembly
assemble
best male
zambales
shambles
```

But several of these outputs don't actually match the query. For example, there is no way to produce the `y` in `assembly` since the `A` in the query must be used to produce the second `s` in the output. Likewise for `shambles`, there is no way to produce both the `h` and the second `s`. 

Rewriting the query in a different form, such as `<blsaemA(e|f)>` does not seem to make a difference. 

Do you have any idea what might be going on? Am I doing something silly?

**Comment by egnor** [comment]
Not silly! See the "Bug" warning here:
https://nutrimatic.org/usage.html#syntax_anagram

I should probably make that more prominent. (Or, you know, fix the bug, but
that's nontrivial...)

**Comment by rdeits** [comment]
Aha, thanks! I had indeed never noticed that warning, but to be fair, this is the first time in many years of using nutrimatic that I had ever encountered a significant number of incorrect results. 

Feel free to close this or keep it open as you see fit. Thanks!

**Comment by egnor** [comment]
Added a link to the warning from the front page usage summary, and resolving this issue -- though of course the underlying problem remains (but it's quite nontrivial to solve).
