### ISSUE TITLE
[Question] Can nutrimatic be built with other latin script based wikipedia languages?

### ISSUE THREAD

**Issue by Honeypot95** [PuzzleTechHub/nutrimatic#9]
Would in theory one be able to just replace the url for the english wikipedia dump to another latin based script wikipedia dump, and do everything else the same to build?

I am only asking about latin script based languages, as I assume things get much more complicated for more exotic scripts.

**Comment by egnor** [comment]
Absolutely possible! Not sure if the code has logic to strip diacritics but if not that's an easy add.

The main challenge will be just getting it running, years elapse between rebuilds and inevitably there's an issue with some library that changed or Wikipedia's dump format or something. But I'm happy to help if you're game to take point on trying it.

**Comment by Honeypot95** [comment]
I managed to do an intermediary step using `iconv` after extracting the text and before building the index. for now, and it seems to work well with the Romanian Wikipedia
```
for f in $(find text -type f)
do
    iconv -f utf-8 -t ascii//TRANSLIT $f | sponge $f
done
```
`sponge` is not POSIX, so that behavior should be replicated with standard tools. Also, wikiextract is now installable from pypi, and the link is dead, so that should be changed in the README. I can do this modification if you want, could be a good first pull request.

**Comment by egnor** [comment]
Sorry for the delay -- yes by all means send a PR!
